favicon: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/cat.jpg
banner: /images/webstack_banner_cn.png

logo:
  expanded: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/cat.jpg
  collapsed: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/cat.jpg
  dark: /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://cn.bing.com/search?q=%s
  thisSearchIcon: url(https://cn.bing.com/favicon.ico)
  hotStatus: true
  data:
    - name: 必应
      img: url(https://cn.bing.com/favicon.ico)
      url: https://cn.bing.com/search?q=%s

# githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 视频平台
    icon: fas fa-play
    config: video
  - name: 站点
    icon: fas fa-globe
    config: hotTools
  - name: magic
    icon: fas fa-star
    config: magic
  - name: BoBOvO
    icon: fas fa-blog
    config: myBlog
# 视频平台
video:
  - name: 抖音
    url: https://www.douyin.com/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/u=1238622637,2627091992&fm=253&fmt=auto&app=138&f=JPEG.webp
    description: 抖音，记录有钱人的美好生活！
  - name: bilibili
    url: https://www.bilibili.com/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/bilibili.png
    description: bilibili!
# 站点
hotTools:
  - name: 阿里巴巴图标库
    url: https://www.iconfont.cn/
    img: https://www.iconfont.cn/favicon.ico
    description: 图标NO.2
  - name: FontAwesome图标
    url: https://fontawesome.com/
    img: https://fontawesome.com/favicon.ico
    description: FA图标
  - name: 腾讯云
    url: https://cloud.tencent.com/
    img: https://cloud.tencent.com/favicon.ico
    description: 腾讯云服务
  - name: 阿里云
    url: https://cn.aliyun.com/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/www.aliyun.com.ico
    description: 阿里云服务
  - name: 51.LA网站统计
    url: https://www.51.la/
    img: https://www.51.la/favicon.ico
    description: 网站数据统计
  - name: Butterfly
    url: https://butterfly.js.org/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/butterfly.js.org.ico
    description: Hexo博客主题
#魔法
magic:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: YouTube
    url: https://www.youtube.com/
    img: https://www.youtube.com/favicon.ico
    description: 油管
  - name: Twitter
    url: https://twitter.com/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/twitter.com.ico
    description: 推特
  - name: magic
    url: https://ikuuu.uk/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/vpn.webp
    description: VPN
# 博客相关
myBlog:
  - name: BoBOvOの小窝
    url: https://demo.bobovo.cc/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/cat.jpg
    description: 属于自己的一片小天地！
  - name: BoBOvO个人主页
    url: https://home.bobovo.cc/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/QQ图片20230129132015.jpg
    description: 个人主页
  - name: Qexo后台
    url: https://qexo.bobovo.cc/
    img: https://cdn.staticaly.com/gh/bob-bzh/picgo_pic@main/img/qexo.png
    description: Hexo博客后台
  - name:
    url:
    img:
    description:
# about:
# url: /about/
# icon: far fa-heart
# name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的demo站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: HCLonely
    url: https://blog.hclonely.com/
    img: /images/logos/myblog.png
    description: 懒人一个
    html: '<br /><blockquote><p>本站是<a href="https://github.com/HCLonely">HCLonely</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2023

busuanzi:
  enable: false
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head:
    |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
